/* eslint-disable @next/next/no-page-custom-font */
import { Toaster } from "react-hot-toast";
import CustomReactQueryProvider from "../ReactQuery/CustomReactQueryProvider";
import { ContextAuthProvider } from "../Context/contextAuth";
import AppLayout from "../Components/AppLayout/AppLayout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&family=Saira:wght@400;500;600;700;800;900&display=swap" />
      </head>
      <body>
        <CustomReactQueryProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <ContextAuthProvider>
            <AppLayout>
              {children}
            </AppLayout>
          </ContextAuthProvider>
        </CustomReactQueryProvider>

      </body>
    </html>
  );
}
